//var json  = {"topic_list":[{"options":[{"question_id":"513efa775558883fbc56ce3d","item_num":"A","item_type":"0","item_value":"a","item_pic":"","unit":"","validate_flag":"","validate_type":"","ID":"513efa775558883fbc56ce3e","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"},{"question_id":"513efa775558883fbc56ce3d","item_num":"B","item_type":"0","item_value":"b","item_pic":"","unit":"","validate_flag":"","validate_type":"","ID":"513efa775558883fbc56ce3f","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"},{"question_id":"513efa775558883fbc56ce3d","item_num":"C","item_type":"1","item_value":"其他","item_pic":"","unit":"单位","validate_flag":"","validate_type":"","ID":"513efa775558883fbc56ce40","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"}],"exam_id":"513efa775558883fbc56ce3c","question_no":1,"question_context":"单选题2","question_type":"0","area_type":"","max_num":0,"min_num":0,"ID":"513efa775558883fbc56ce3d","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"},{"options":[{"question_id":"513efa775558883fbc56ce41","item_num":"A","item_type":"0","item_value":"aa","item_pic":"","unit":"","validate_flag":"","validate_type":"","ID":"513efa775558883fbc56ce42","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"},{"question_id":"513efa775558883fbc56ce41","item_num":"B","item_type":"0","item_value":"bb","item_pic":"","unit":"","validate_flag":"","validate_type":"","ID":"513efa775558883fbc56ce43","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"},{"question_id":"513efa775558883fbc56ce41","item_num":"C","item_type":"0","item_value":"cc","item_pic":"","unit":"","validate_flag":"","validate_type":"","ID":"513efa775558883fbc56ce44","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"}],"exam_id":"513efa775558883fbc56ce3c","question_no":2,"question_context":"多选题1","question_type":"1","area_type":"","max_num":1,"min_num":1,"ID":"513efa775558883fbc56ce41","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"},{"options":[{"question_id":"513efa775558883fbc56ce45","item_num":"A","item_type":"0","item_value":"a","item_pic":"","unit":"","validate_flag":"","validate_type":"","ID":"513efa775558883fbc56ce46","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"},{"question_id":"513efa775558883fbc56ce45","item_num":"B","item_type":"0","item_value":"b","item_pic":"","unit":"","validate_flag":"","validate_type":"","ID":"513efa775558883fbc56ce47","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"},{"question_id":"513efa775558883fbc56ce45","item_num":"C","item_type":"0","item_value":"c","item_pic":"","unit":"","validate_flag":"","validate_type":"","ID":"513efa775558883fbc56ce48","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"}],"exam_id":"513efa775558883fbc56ce3c","question_no":3,"question_context":"单选题1","question_type":"0","area_type":"","max_num":0,"min_num":0,"ID":"513efa775558883fbc56ce45","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"},{"exam_id":"513efa775558883fbc56ce3c","question_no":4,"question_context":"地区题2","question_type":"4","area_type":"2","max_num":0,"min_num":0,"ID":"513efa775558883fbc56ce49","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"},{"exam_id":"513efa775558883fbc56ce3c","question_no":5,"question_context":"开放题2","question_type":"3","area_type":"","max_num":0,"min_num":0,"ID":"513efa785558883fbc56ce4a","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:48","UPDATE_TIME":"2013-3-12 17:50:48"},{"exam_id":"513efa775558883fbc56ce3c","question_no":6,"question_context":"开放题1","question_type":"3","area_type":"","max_num":0,"min_num":0,"ID":"513efa785558883fbc56ce4b","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:48","UPDATE_TIME":"2013-3-12 17:50:48"},{"options":[{"question_id":"513efa785558883fbc56ce4c","item_num":"A","item_type":"0","item_value":"aa","item_pic":"","unit":"","validate_flag":"","validate_type":"","ID":"513efa785558883fbc56ce4d","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:48","UPDATE_TIME":"2013-3-12 17:50:48"},{"question_id":"513efa785558883fbc56ce4c","item_num":"B","item_type":"0","item_value":"bb","item_pic":"","unit":"","validate_flag":"","validate_type":"","ID":"513efa785558883fbc56ce4e","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:48","UPDATE_TIME":"2013-3-12 17:50:48"},{"question_id":"513efa785558883fbc56ce4c","item_num":"C","item_type":"0","item_value":"cc","item_pic":"","unit":"","validate_flag":"","validate_type":"","ID":"513efa785558883fbc56ce4f","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:48","UPDATE_TIME":"2013-3-12 17:50:48"},{"question_id":"513efa785558883fbc56ce4c","item_num":"D","item_type":"0","item_value":"dd","item_pic":"","unit":"","validate_flag":"","validate_type":"","ID":"513efa785558883fbc56ce50","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:48","UPDATE_TIME":"2013-3-12 17:50:48"},{"question_id":"513efa785558883fbc56ce4c","item_num":"E","item_type":"1","item_value":"补充","item_pic":"","unit":"","validate_flag":"","validate_type":"","ID":"513efa785558883fbc56ce51","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:48","UPDATE_TIME":"2013-3-12 17:50:48"}],"exam_id":"513efa775558883fbc56ce3c","question_no":7,"question_context":"多选题2","question_type":"1","area_type":"","max_num":1,"min_num":1,"ID":"513efa785558883fbc56ce4c","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:48","UPDATE_TIME":"2013-3-12 17:50:48"},{"exam_id":"513efa775558883fbc56ce3c","question_no":8,"question_context":"地区题1","question_type":"4","area_type":"1","max_num":0,"min_num":0,"ID":"513efa785558883fbc56ce52","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:48","UPDATE_TIME":"2013-3-12 17:50:48"}],"result_id":"513f1af15558e4bc54c3e368","email":"aaa@163.com","question_name":"测试问卷2","question_no":"test2","client_id":"宝马","end_date":"2013-1-13 0:03:00","template_id":"2","public_pic":"C:\\fakepath\\26.jpg","face_page":"","logo":"","join_point":6,"complate_point":8,"examination_type":"2","quota":0,"examination_detail":"问卷说明","remark":"备注","status":"","ques_count":8,"company":"","question_html":"<ul style='list-style-type: none'><dl>             <dt>                 <span>1</span>.单选题2             </dt>             <dd class=\"option-list\">             <input type=\"radio\" name=\"2/\"> A.a<input type=\"radio\" name=\"2/\"> B.bC.其他<textarea></textarea>单位</dd>             <div style=\"text-align: right; border-bottom: 1px solid #ccc;\">                 <input type=\"checkbox\" class=\"add-break\">分页&nbsp;&nbsp;                 <a class=\"remove-question\" href=\"#\">删除</a>&nbsp;&nbsp;                 <a class=\"edit-question\" href=\"#\">修改</a>             </div>         </dl><dl>             <dt>                 <span>2</span>.多选题1             </dt>             <dd class=\"option-list\">             <input type=\"checkbox\" name=\"3/\"> A.aa<input type=\"checkbox\" name=\"3/\"> B.bb<input type=\"checkbox\" name=\"3/\"> C.cc</dd>             <div style=\"text-align: right; border-bottom: 1px solid #ccc;\">                 <input type=\"checkbox\" class=\"add-break\">分页&nbsp;&nbsp;                 <a class=\"remove-question\" href=\"#\">删除</a>&nbsp;&nbsp;                 <a class=\"edit-question\" href=\"#\">修改</a>             </div>         </dl><dl style=\"\" class=\"\">             <dt>                 <span>3</span>.单选题1             </dt>             <dd class=\"option-list\">             <input type=\"radio\" name=\"1/\"> A.a<input type=\"radio\" name=\"1/\"> B.b<input type=\"radio\" name=\"1/\"> C.c</dd>             <div style=\"text-align: right; border-bottom: 1px solid #ccc;\">                 <input type=\"checkbox\" class=\"add-break\">分页&nbsp;&nbsp;                 <a class=\"remove-question\" href=\"#\">删除</a>&nbsp;&nbsp;                 <a class=\"edit-question\" href=\"#\">修改</a>             </div>         </dl><dl style=\"\" class=\"\">             <dt>                 <span>4</span>.地区题2             </dt>             <dd class=\"option-list\">             <select class=\"province\"><option>请选择</option><option value=\"340000\">安徽省</option><option value=\"110000\">北京市</option><option value=\"350000\">福建省</option><option value=\"620000\">甘肃省</option><option value=\"440000\">广东省</option><option value=\"450000\">广西壮族自治区</option><option value=\"520000\">贵州省</option><option value=\"460000\">海南省</option><option value=\"130000\">河北省</option><option value=\"410000\">河南省</option><option value=\"230000\">黑龙江省</option><option value=\"420000\">湖北省</option><option value=\"430000\">湖南省</option><option value=\"220000\">吉林省</option><option value=\"320000\">江苏省</option><option value=\"360000\">江西省</option><option value=\"210000\">辽宁省</option><option value=\"150000\">内蒙古自治区</option><option value=\"640000\">宁夏回族自治区</option><option value=\"630000\">青海省</option><option value=\"370000\">山东省</option><option value=\"140000\">山西省</option><option value=\"610000\">陕西省</option><option value=\"310000\">上海市</option><option value=\"510000\">四川省</option><option value=\"120000\">天津市</option><option value=\"540000\">西藏自治区</option><option value=\"650000\">新疆维吾尔自治区</option><option value=\"530000\">云南省</option><option value=\"330000\">浙江省</option><option value=\"500000\">重庆市</option></select>省\n        <select class=\"city\"><option>请选择</option></select>市\n    \n        <select class=\"district\"><option>请选择</option></select>区\n    </dd>             <div style=\"text-align: right; border-bottom: 1px solid #ccc;\">                 <input type=\"checkbox\" class=\"add-break\">分页&nbsp;&nbsp;                 <a class=\"remove-question\" href=\"#\">删除</a>&nbsp;&nbsp;                 <a class=\"edit-question\" href=\"#\">修改</a>             </div>         </dl><dl style=\"\" class=\"\">             <dt>                 <span>5</span>.开放题2             </dt>             <dd class=\"option-list\">             <textarea></textarea></dd>             <div style=\"text-align: right; border-bottom: 1px solid #ccc;\">                 <input type=\"checkbox\" class=\"add-break\">分页&nbsp;&nbsp;                 <a class=\"remove-question\" href=\"#\">删除</a>&nbsp;&nbsp;                 <a class=\"edit-question\" href=\"#\">修改</a>             </div>         </dl><dl style=\"\" class=\"\">             <dt>                 <span>6</span>.开放题1             </dt>             <dd class=\"option-list\">             <input type=\"text\"></dd>             <div style=\"text-align: right; border-bottom: 1px solid #ccc;\">                 <input type=\"checkbox\" class=\"add-break\">分页&nbsp;&nbsp;                 <a class=\"remove-question\" href=\"#\">删除</a>&nbsp;&nbsp;                 <a class=\"edit-question\" href=\"#\">修改</a>             </div>         </dl><dl>             <dt>                 <span>7</span>.多选题2             </dt>             <dd class=\"option-list\">             <input type=\"checkbox\" name=\"4/\"> A.aa<input type=\"checkbox\" name=\"4/\"> B.bb<input type=\"checkbox\" name=\"4/\"> C.cc<input type=\"checkbox\" name=\"4/\"> D.ddE.补充<textarea></textarea></dd>             <div style=\"text-align: right; border-bottom: 1px solid #ccc;\">                 <input type=\"checkbox\" class=\"add-break\">分页&nbsp;&nbsp;                 <a class=\"remove-question\" href=\"#\">删除</a>&nbsp;&nbsp;                 <a class=\"edit-question\" href=\"#\">修改</a>             </div>         </dl><dl>             <dt>                 <span>8</span>.地区题1             </dt>             <dd class=\"option-list\">             <select class=\"province\"><option>请选择</option><option value=\"340000\">安徽省</option><option value=\"110000\">北京市</option><option value=\"350000\">福建省</option><option value=\"620000\">甘肃省</option><option value=\"440000\">广东省</option><option value=\"450000\">广西壮族自治区</option><option value=\"520000\">贵州省</option><option value=\"460000\">海南省</option><option value=\"130000\">河北省</option><option value=\"410000\">河南省</option><option value=\"230000\">黑龙江省</option><option value=\"420000\">湖北省</option><option value=\"430000\">湖南省</option><option value=\"220000\">吉林省</option><option value=\"320000\">江苏省</option><option value=\"360000\">江西省</option><option value=\"210000\">辽宁省</option><option value=\"150000\">内蒙古自治区</option><option value=\"640000\">宁夏回族自治区</option><option value=\"630000\">青海省</option><option value=\"370000\">山东省</option><option value=\"140000\">山西省</option><option value=\"610000\">陕西省</option><option value=\"310000\">上海市</option><option value=\"510000\">四川省</option><option value=\"120000\">天津市</option><option value=\"540000\">西藏自治区</option><option value=\"650000\">新疆维吾尔自治区</option><option value=\"530000\">云南省</option><option value=\"330000\">浙江省</option><option value=\"500000\">重庆市</option></select>省\n        <select class=\"city\"><option>请选择</option></select>市\n    </dd>             <div style=\"text-align: right; border-bottom: 1px solid #ccc;\">                 <input type=\"checkbox\" class=\"add-break\">分页&nbsp;&nbsp;                 <a class=\"remove-question\" href=\"#\">删除</a>&nbsp;&nbsp;                 <a class=\"edit-question\" href=\"#\">修改</a>             </div>         </dl></ul>","logic_control_js":"","quota_control_js":"","ID":"513efa775558883fbc56ce3c","VERSION":1,"DEL_FLG":"N","INSERT_TIME":"2013-3-12 17:50:47","UPDATE_TIME":"2013-3-12 17:50:47"};
//var json = {"ID":"","question_no":"","question_name":"","client_id":"请选择","public_pic":"","end_date":"","face_page":"","logo":"","template_id":"0","join_point":null,"complate_point":null,"examination_type":"0","examination_detail":"","quota":0,"ques_count":8,"company":"","remark":"","status":"","question_html":"<dl>             <dt>                 <span>1</span>.第一题单选题             </dt>             <dd class=\"option-list\">             <div class=\"option_horizontal\"><input type=\"radio\" name=\"1/\"> A.阿斯达</div><div class=\"option_horizontal\"><input type=\"radio\" name=\"1/\"> B.的双方各</div><div class=\"option_horizontal\"><input type=\"radio\" name=\"1/\"> C.萨达</div><div class=\"option_horizontal\"><input type=\"radio\" name=\"1/\"> D.股股份</div></dd>                      </dl><dl>             <dt>                 <span>2</span>.第二题单选题             </dt>             <dd class=\"option-list\">             <div class=\"checkbox\"><input type=\"checkbox\" name=\"2/\"> A.按时大大</div><div class=\"checkbox\"><input type=\"checkbox\" name=\"2/\"> B.话费陡峭的</div><div class=\"checkbox\"><input type=\"checkbox\" name=\"2/\"> C.的搜噶</div><div class=\"text-area\"><input type=\"checkbox\" name=\"2/\">D.阿萨德发顺丰<textarea></textarea></div></dd>                      </dl><dl>             <dt>                 <span>3</span>.第三题多选题             </dt>             <dd class=\"option-list\">             <div class=\"checkbox\"><input type=\"checkbox\" name=\"3/\"> A.撒大多数</div><div class=\"checkbox\"><input type=\"checkbox\" name=\"3/\"> B.电光火石</div><div class=\"checkbox\"><input type=\"checkbox\" name=\"3/\"> C.萨达</div><div class=\"checkbox\"><input type=\"checkbox\" name=\"3/\"> D.爱的萨芬</div></dd>             <div style=\"text-align: right; border-bottom: 1px solid #ccc;\" class=\"questionary_list_opera\">分页</div>         </dl><dl>             <dt>                 <span>4</span>.第四题多选题             </dt>             <dd class=\"option-list\">             <div class=\"radio\"><input type=\"radio\" name=\"4/\"> A.啊盛大的撒</div><div class=\"radio\"><input type=\"radio\" name=\"4/\"> B.撒大大</div><div class=\"radio\"><input type=\"radio\" name=\"4/\"> C.萨达</div><div class=\"text-area\"><input type=\"radio\" name=\"4/\">D.玉兔精<textarea></textarea></div></dd>                      </dl><dl>             <dt>                 <span>5</span>.第五题开放题             </dt>             <dd class=\"option-list\">             <input type=\"text\"></dd>                      </dl><dl>             <dt>                 <span>6</span>.第六题开放题             </dt>             <dd class=\"option-list\">             <textarea></textarea></dd>             <div style=\"text-align: right; border-bottom: 1px solid #ccc;\" class=\"questionary_list_opera\">分页</div>         </dl><dl>             <dt>                 <span>7</span>.第七题地区题省市             </dt>             <dd class=\"option-list\">             <select class=\"province\"><option>请选择</option></select>         省\n        <select class=\"city\">\n            <option>请选择</option>\n        </select>\n        市\n    </dd>                      </dl><dl>             <dt>                 <span>8</span>.第八题地区题省市区             </dt>             <dd class=\"option-list\">             <select class=\"province\"><option>请选择</option></select>         省\n        <select class=\"city\">\n            <option>请选择</option>\n        </select>\n        市\n    \n        <select class=\"district\">\n            <option>请选择</option>\n        </select>\n        区\n    </dd>                      </dl>","logic_control_js":"","quota_control_js":"","topic_list":[{"question_no":1,"question_context":"第一题单选题","question_type":"0","allow_bland":"N","max_num":0,"min_num":0,"area_type":"","options":[{"item_num":"A","item_type":"0","item_value":"阿斯达","item_pic":"","unit":"","validate_flag":"","validate_type":""},{"item_num":"B","item_type":"0","item_value":"的双方各","item_pic":"","unit":"","validate_flag":"","validate_type":""},{"item_num":"C","item_type":"0","item_value":"萨达","item_pic":"","unit":"","validate_flag":"","validate_type":""},{"item_num":"D","item_type":"0","item_value":"股股份","item_pic":"","unit":"","validate_flag":"","validate_type":""}]},{"question_no":2,"question_context":"第二题单选题","question_type":"1","allow_bland":"N","max_num":"1","min_num":"1","area_type":"","options":[{"item_num":"A","item_type":"0","item_value":"按时大大","item_pic":"","unit":"","validate_flag":"","validate_type":""},{"item_num":"B","item_type":"0","item_value":"话费陡峭的","item_pic":"","unit":"","validate_flag":"","validate_type":""},{"item_num":"C","item_type":"0","item_value":"的搜噶","item_pic":"","unit":"","validate_flag":"","validate_type":""},{"item_num":"D","item_type":"1","item_value":"阿萨德发顺丰","item_pic":"","unit":"","validate_flag":"","validate_type":""}]},{"question_no":3,"question_context":"第三题多选题","question_type":"1","allow_bland":"N","max_num":"1","min_num":"1","area_type":"","options":[{"item_num":"A","item_type":"0","item_value":"撒大多数","item_pic":"","unit":"","validate_flag":"","validate_type":""},{"item_num":"B","item_type":"0","item_value":"电光火石","item_pic":"","unit":"","validate_flag":"","validate_type":""},{"item_num":"C","item_type":"0","item_value":"萨达","item_pic":"","unit":"","validate_flag":"","validate_type":""},{"item_num":"D","item_type":"0","item_value":"爱的萨芬","item_pic":"","unit":"","validate_flag":"","validate_type":""}]},{"question_no":4,"question_context":"第四题多选题","question_type":"0","allow_bland":"N","max_num":0,"min_num":0,"area_type":"","options":[{"item_num":"A","item_type":"0","item_value":"啊盛大的撒","item_pic":"","unit":"","validate_flag":"","validate_type":""},{"item_num":"B","item_type":"0","item_value":"撒大大","item_pic":"","unit":"","validate_flag":"","validate_type":""},{"item_num":"C","item_type":"0","item_value":"萨达","item_pic":"","unit":"","validate_flag":"","validate_type":""},{"item_num":"D","item_type":"1","item_value":"玉兔精","item_pic":"","unit":"","validate_flag":"","validate_type":""}]},{"question_no":5,"question_context":"第五题开放题","question_type":"3","allow_bland":"N","max_num":0,"min_num":0,"area_type":"","options":[]},{"question_no":6,"question_context":"第六题开放题","question_type":"3","allow_bland":"N","max_num":0,"min_num":0,"area_type":"","options":[]},{"question_no":7,"question_context":"第七题地区题省市","question_type":"4","allow_bland":"N","max_num":0,"min_num":0,"area_type":"1","options":[]},{"question_no":8,"question_context":"第八题地区题省市区","question_type":"4","allow_bland":"N","max_num":0,"min_num":0,"area_type":"2","options":[]}],"result_id":"","email":""};
var json = {
	"topic_list": [{
		"question_no": 1,
		"question_context": "第一题",
		"question_type": "0",
		"allow_bland": "N",
		"max_num": 0,
		"min_num": 0,
		"area_type": "",
		"options": [{
			"item_num": "A",
			"item_type": "0",
			"item_value": "aa",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}, {
			"item_num": "B",
			"item_type": "0",
			"item_value": "bb",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}, {
			"item_num": "C",
			"item_type": "0",
			"item_value": "cc",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}, {
			"item_num": "D",
			"item_type": "0",
			"item_value": "dd",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}]
	}, {
		"question_no": 2,
		"question_context": "第二题",
		"question_type": "1",
		"allow_bland": "N",
		"max_num": "1",
		"min_num": "1",
		"area_type": "",
		"options": [{
			"item_num": "A",
			"item_type": "0",
			"item_value": "fsa",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}, {
			"item_num": "B",
			"item_type": "0",
			"item_value": "fsdfds",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}, {
			"item_num": "C",
			"item_type": "0",
			"item_value": "12f",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}, {
			"item_num": "D",
			"item_type": "1",
			"item_value": "",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}]
	}, {
		"question_no": 3,
		"question_context": "第三题",
		"question_type": "1",
		"allow_bland": "N",
		"max_num": "1",
		"min_num": "1",
		"area_type": "",
		"options": [{
			"item_num": "A",
			"item_type": "0",
			"item_value": "sdf",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}, {
			"item_num": "B",
			"item_type": "0",
			"item_value": "fwefwe",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}, {
			"item_num": "C",
			"item_type": "0",
			"item_value": "fdgfd",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}, {
			"item_num": "D",
			"item_type": "0",
			"item_value": "gag",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}]
	}, {
		"question_no": 4,
		"question_context": "第四题",
		"question_type": "0",
		"allow_bland": "N",
		"max_num": 0,
		"min_num": 0,
		"area_type": "",
		"options": [{
			"item_num": "A",
			"item_type": "0",
			"item_value": "sdfs",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}, {
			"item_num": "B",
			"item_type": "0",
			"item_value": "fewfe",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}, {
			"item_num": "C",
			"item_type": "0",
			"item_value": "fsdafs",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}, {
			"item_num": "D",
			"item_type": "0",
			"item_value": "wqe4t",
			"item_pic": "",
			"unit": "",
			"validate_flag": "",
			"validate_type": ""
		}]
	}, {
		"question_no": 5,
		"question_context": "第五题",
		"question_type": "3",
		"allow_bland": "N",
		"max_num": 0,
		"min_num": 0,
		"area_type": "",
		"options": []
	}, {
		"question_no": 6,
		"question_context": "第六题",
		"question_type": "3",
		"allow_bland": "N",
		"max_num": 0,
		"min_num": 0,
		"area_type": "",
		"options": []
	}, {
		"question_no": 7,
		"question_context": "第七题",
		"question_type": "4",
		"allow_bland": "N",
		"max_num": 0,
		"min_num": 0,
		"area_type": "1",
		"options": []
	}, {
		"question_no": 8,
		"question_context": "第八题",
		"question_type": "4",
		"allow_bland": "N",
		"max_num": 0,
		"min_num": 0,
		"area_type": "2",
		"options": []
	}],
	"result_id": "5141c914e4b0a26955cd64f7",
	"email": "aaa@163.com",
	"question_name": "john_test1",
	"question_no": "john_test1_no",
	"client_id": "宝洁",
	"end_date": "Jan 14, 2013 12:03:00 AM",
	"template_id": "0",
	"public_pic": "",
	"face_page": "",
	"logo": "",
	"examination_type": "0",
	"quota": 0,
	"examination_detail": "",
	"remark": "",
	"status": "",
	"ques_count": 4,
	"company": "",
	"question_html": "<dl>             <dt>                 <span>1</span>.第一题单选题             </dt>             <dd class=\"option-list\">             <div class=\"option_horizontal\"><input type=\"radio\" name=\"1/\"> A.阿斯达</div><div class=\"option_horizontal\"><input type=\"radio\" name=\"1/\"> B.的双方各</div><div class=\"option_horizontal\"><input type=\"radio\" name=\"1/\"> C.萨达</div><div class=\"option_horizontal\"><input type=\"radio\" name=\"1/\"> D.股股份</div></dd>                      </dl><dl>             <dt>                 <span>2</span>.第二题单选题             </dt>             <dd class=\"option-list\">             <div class=\"checkbox\"><input type=\"checkbox\" name=\"2/\"> A.按时大大</div><div class=\"checkbox\"><input type=\"checkbox\" name=\"2/\"> B.话费陡峭的</div><div class=\"checkbox\"><input type=\"checkbox\" name=\"2/\"> C.的搜噶</div><div class=\"text-area\"><input type=\"checkbox\" name=\"2/\">D.阿萨德发顺丰<textarea></textarea></div></dd>                      </dl><dl>             <dt>                 <span>3</span>.第三题多选题             </dt>             <dd class=\"option-list\">             <div class=\"checkbox\"><input type=\"checkbox\" name=\"3/\"> A.撒大多数</div><div class=\"checkbox\"><input type=\"checkbox\" name=\"3/\"> B.电光火石</div><div class=\"checkbox\"><input type=\"checkbox\" name=\"3/\"> C.萨达</div><div class=\"checkbox\"><input type=\"checkbox\" name=\"3/\"> D.爱的萨芬</div></dd>             <div style=\"text-align: right; border-bottom: 1px solid #ccc;\" class=\"questionary_list_opera\">分页</div>         </dl><dl>             <dt>                 <span>4</span>.第四题多选题             </dt>             <dd class=\"option-list\">             <div class=\"radio\"><input type=\"radio\" name=\"4/\"> A.啊盛大的撒</div><div class=\"radio\"><input type=\"radio\" name=\"4/\"> B.撒大大</div><div class=\"radio\"><input type=\"radio\" name=\"4/\"> C.萨达</div><div class=\"text-area\"><input type=\"radio\" name=\"4/\">D.玉兔精<textarea></textarea></div></dd>                      </dl><dl>             <dt>                 <span>5</span>.第五题开放题             </dt>             <dd class=/\"option-list/\">             <input type=\"text\"></dd>                      </dl><dl>             <dt>                 <span>6</span>.第六题开放题             </dt>             <dd class=\"option-list\">             <textarea></textarea></dd>             <div style=\"text-align: right; border-bottom: 1px solid #ccc;\" class=\"questionary_list_opera\">分页</div>         </dl><dl>             <dt>                 <span>7</span>.第七题地区题省市             </dt>             <dd class=\"option-list\">             <select class=\"province\"><option value=\"0\">请选择</option></select>         省<select class=\"city\">    <option value=\"0\">请选择</option>    </select>市</dd>                      </dl><dl>             <dt>                 <span>8</span>.第八题地区题省市区             </dt>             <dd class=\"option-list\">             <select class=\"province\"><option value=\"0\">请选择</option></select>         省    <select class=\"city\">        <option value=\"0\">请选择</option>    </select>市    <select class=\"district\">        <option value=\"0\">请选择</option>    </select>区</dd>                      </dl>",
	"logic_control_js": "[{\"logicName\":\"逻辑一\",\"logicType\":\"0\",\"map\":{\"0\":[\"-2\"]},\"action\":{\"type\":\"0\",\"queN\":\"1\",\"optN\":\"\"}},{\"logicName\":\"逻辑二\",\"logicType\":\"1\",\"map\":{\"0\":[\"-2\"]},\"action\":{\"type\":\"0\",\"queN\":\"1\",\"optN\":\"\"}}]",
	"quota_control_js": "",
	"ID": "5141c563e4b0a26955cd64dc",
	"VERSION": 1,
	"DEL_FLG": "N",
	"INSERT_TIME": "Mar 14, 2013 8:41:07 PM",
	"UPDATE_TIME": "Mar 14, 2013 8:41:07 PM"
};